### ISSUE TITLE
Hard-coded path

### ISSUE THREAD

**Issue by vincadrn** [vincadrn/signal-processing-final#1]
## Issue
Hard-coded path in [this line](https://github.com/vincadrn/signal-processing-final/blob/5ae67a9282daf5b63114d63c93aed3d1c4d285d9/mainwindow.py#L12), causing this error when run:
```
Traceback (most recent call last):
  File "C:\Users\Lenovo\Documents\signal-processing-final\mainwindow.py", line 355, in <module>
    e = MainWindow(window)
  File "C:\Users\Lenovo\Documents\signal-processing-final\mainwindow.py", line 35, in __init__
    self.image_image_1 = PhotoImage(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 4062, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 4007, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "D:\build\assets\frame0\image_1.png": no such file or directory
```

## Solution
Please create another folder with a name as you see fit, e.g. `assets`, to contain all the assets needed for the app (fonts, images, icons, resources, etc.).

**Comment by heliumonoxide** [comment]
Ok, will do
